---
http:
  address: "127.0.0.1:8080"
  timeout:
    read: 5
    write: 5

log:
  level: "info"
  format: "json"

database:
  host: "localhost"
  port: "5432"
  name: "gapi"
  user: "postgres"
  password: "password"
